### ISSUE TITLE
Confirmable E-Mail and Fix Show Posts

### ISSUE THREAD

**Issue by BlazeDex** [BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final#25]
When the users creates a new account, they must receive a confirmation link in their e-mail to log in. In addition, the users can introduce their full names in the form.
```[tasklist]
### Tasks
- [x] Use ActionMailer to send the e-mails.
- [x] Add confirmable validation on User model.
- [x] Add an input to save user's name.
- [x] Add an input to save user's lastname.
- [x] Fix bug, the current user cannot see posts from other users.
```
