### ISSUE TITLE
Create Database Models

### ISSUE THREAD

**Issue by BlazeDex** [BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final#3]
```[tasklist]
### Tasks
- [x] Create Databases
- [x] Create model for User
- [x] Create model for Routine
- [x] Create models for Serie
- [x] Create model for Post
- [x] Create models for Message
- [x] Create models for Comment
- [x] Create model for Likes
- [x] Create model for Followers
```

**Comment by BlazeDex** [comment]
![Image](https://github.com/BrightCoders-Institute/s10a1-proyecto-final-team-03-s10a1-proyecto-final/assets/73453092/16896020-6920-4615-9f59-4a2f662f59d8)
